# ASSIGNMENT CONFIG
config_file: ../../../assign_config.yml
files:
    - cal_fb.csv
generate:
    points_possible: 100.0
export_cell:
    pdf: false

# Homework 5: Applying Functions and Iteration

Please complete this notebook by filling in the cells provided. Before you begin, execute the previous cell to load the provided tests.

**Helpful Resource:**
- [Python Reference](https://www.data8.org/reference/): Cheat sheet of helpful array & table methods used in Data 8!

**Recommended Readings**: 

* [Tabular Thinking Guide](https://drive.google.com/file/d/1QolEBR9azk18R7U3Ls8IZKfwrMM7IxYN/view?usp=drive_link)
* [Applying Functions](https://www.inferentialthinking.com/chapters/08/1/Applying_a_Function_to_a_Column.html)
* [Conditionals](https://www.inferentialthinking.com/chapters/09/1/Conditional_Statements.html)
* [Iteration](https://www.inferentialthinking.com/chapters/09/2/Iteration.html)

Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell to setup the notebook by importing some helpful libraries. Each time you start your server, you will need to execute this cell again.

For all problems that you must write explanations and sentences for, you **must** provide your answer in the designated space. **Moreover, throughout this homework and all future ones, please be sure to not re-assign variables throughout the notebook!** For example, if you use `max_temperature` in your answer to one question, do not reassign it later on. Otherwise, you will fail tests that you thought you were passing previously!


**Note: This homework has hidden tests on it. That means even though the tests may say 100% passed, it doesn't mean your final grade will be 100%. We will be running more tests for correctness once everyone turns in the homework.**


Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged. 

You should start early so that you have time to get help if you're stuck.

## 1. 2021 Cal Football Season

In [1]:
# Run this cell to set up the notebook, but please don't change it.

# These lines import the numpy and datascience modules.
import numpy as np
from datascience import *
import warnings
warnings.simplefilter('ignore', FutureWarning)

James is trying to analyze how well the Cal football team performed in the 2021 season. A football game is divided into four periods, called quarters. The number of points Cal scored in each quarter and the number of points their opponent scored in each quarter are stored in a table called `cal_fb.csv`.

In [2]:
# Just run this cell
# Read in the cal_fb csv file
games = Table().read_table("cal_fb.csv")
games.show()

# BEGIN QUESTION
name: q1_1
manual: false
points:
 - 10
 - 10

Let's start by finding the total points each team scored in a game.

**Question 1.** Write a function called `sum_scores`.  It should take four arguments, where each argument represents integers corresponding to the team's score for each quarter. It should return the team's total score for that game. **(20 Points)**

*Note:* Don't overthink this question!

# BEGIN SOLUTION

In [3]:
""" # BEGIN PROMPT
def sum_scores(...):
    '''Returns the total score calculated by adding up the score of each quarter'''
    ...
"""; # END PROMPT
# BEGIN SOLUTION NO PROMPT
def sum_scores(q1, q2, q3, q4):
    return q1 + q2 + q3 + q4
# END SOLUTION

sum_scores(14, 7, 3, 0) #DO NOT CHANGE THIS LINE

24

# END SOLUTION

# BEGIN TESTS

In [4]:
sum_scores(2, 3, 6, 1)

12

In [5]:
sum_scores(-2,3,5,-10)

-4

# END TESTS

# END QUESTION

# BEGIN QUESTION
name: q1_2
manual: false
points:
 - 0
 - 0
 - 20

**Question 2.** Create a new table `final_scores` with three columns in this *specific* order: `Opponent`, `Cal Score`, `Opponent Score`. You will have to create the `Cal Score` and `Opponent Score` columns. Use the function `sum_scores` you just defined in the previous question for this problem. **(20 Points)**

*Hint:* If you want to apply a function that takes in multiple arguments, you can pass multiple column names as arguments in `tbl.apply()`. The column values will be passed into the corresponding arguments of the function. Take a look at the Python Reference Sheet and Lecture 13's demo for syntax.

*Note:* If you’re running into issues creating `final_scores`, check that `cal_scores` and `opponent_scores` output what you want.

# BEGIN SOLUTION

In [6]:
cal_scores = games.apply(sum_scores, "Cal 1Q","Cal 2Q", "Cal 3Q", "Cal 4Q") # SOLUTION
opponent_scores = games.apply(sum_scores, "Opp 1Q", "Opp 2Q", "Opp 3Q", "Opp 4Q") # SOLUTION
final_scores = games.with_columns("Cal Score", cal_scores, "Opponent Score", opponent_scores).select("Opponent", "Cal Score", "Opponent Score") # SOLUTION
final_scores

Opponent         | Cal Score | Opponent Score
Nevada           | 17        | 22
TCU              | 32        | 34
Sacramento State | 42        | 30
Washington       | 24        | 31
Washington State | 6         | 21
Oregon           | 17        | 24
Colorado         | 26        | 3
Oregon State     | 39        | 25
Arizona          | 3         | 10
Stanford         | 41        | 11
... (2 rows omitted)

# END SOLUTION

# BEGIN TESTS

In [7]:
final_scores.num_columns

3

In [8]:
set(['Opponent', 'Cal Score', 'Opponent Score']) == set(final_scores.labels)

True

In [9]:
# HIDDEN
final_scores.take(range(5, 11))

Opponent     | Cal Score | Opponent Score
Oregon       | 17        | 24
Colorado     | 26        | 3
Oregon State | 39        | 25
Arizona      | 3         | 10
Stanford     | 41        | 11
UCLA         | 14        | 42

# END TESTS

# END QUESTION

We can get specific row objects from a table. You can use `tbl.row(n)` to get the `n`th row of a table. `row.item("column_name")` will allow you to select the element that corresponds to `column_name` in a particular row. Here's an example:

In [10]:
# Just run this cell
# We got the Axe!
games.row(9)

Row(Opponent='Stanford', Cal 1Q=0, Cal 2Q=14, Cal 3Q=13, Cal 4Q=14, Opp 1Q=0, Opp 2Q=3, Opp 3Q=0, Opp 4Q=8)

In [11]:
# Just run this cell
games.row(9).item("Cal 4Q")

14

# BEGIN QUESTION
name: q1_3
manual: false
points:
 - 0
 - 10
 - 10

**Question 3.** We want to see for a particular game whether or not Cal lost. Write a function called `did_cal_lose`.  It should take one argument: a **row object** from the `final_scores` table. It should return either `True` if Cal's score was less than the Opponent's score, and `False` otherwise. **(20 Points)**

*Note 1*: "Row object" means a row from the table that contains all the data for that specific row. It is **not** the index of a row. Do not try and call `final_scores.row(row)` inside of the function.

*Note 2*: If you're still confused by row objects, try printing out `final_scores.row(1)` in a new cell to visually see what it looks like! This piece of code is pulling out the row object located at index 1 of the `final_scores` table and returning it. When you display it in a cell, you'll see that it is not located within a table, but is instead a standalone row object!

# BEGIN SOLUTION

In [12]:
""" # BEGIN PROMPT
def did_cal_lose(row):
    ...
"""; # END PROMPT
# BEGIN SOLUTION NO PROMPT
def did_cal_lose(row):
    return row.item("Cal Score") < row.item("Opponent Score")
# END SOLUTION

did_cal_lose(final_scores.row(1)) #DO NOT CHANGE THIS LINE

True

# END SOLUTION

# BEGIN TESTS

In [13]:
'did_cal_lose' in globals()

True

In [14]:
did_cal_lose(final_scores.row(1))

True

In [15]:
# HIDDEN
did_cal_lose(final_scores.row(6))

False

# END TESTS

# END QUESTION

# BEGIN QUESTION
name: q1_4
manual: false
points:
 - 0
 - 0
 - 10
 - 10

**Question 4.** James wants to see how Cal did against every opponent during the 2021 season. Using the `final_scores` table:

1. Assign `results` to an array of `True` and `False` values that correspond to whether or not Cal lost.
2. Add the `results` array to the `final_scores` table in a column named `Results`, and assign this to `final_scores_with_results`.
3. Then, respectively assign the number of wins and losses Cal had to `cal_wins` and `cal_losses`.

**(20 Points)**

*Hint 1*: `True` and `False` are **not** strings. What data type are they?

*Hint 2*: `tbl.num_rows` might be helpful too.

*Hint 3*: When you only pass a function name and no column labels through `tbl.apply()`, the function gets applied to every row in `tbl`.

# BEGIN SOLUTION

In [16]:
results = final_scores.apply(did_cal_lose) # SOLUTION
final_scores_with_results = final_scores.with_columns("Results", results) # SOLUTION
cal_losses = final_scores_with_results.where("Results", True).num_rows # SOLUTION
cal_wins = final_scores_with_results.num_rows - cal_losses # SOLUTION

# Don't delete or edit the following line:
print(f"In the 2021 Season, Cal Football won {cal_wins} games and lost {cal_losses} games. Go Bears! 🐻")

In the 2021 Season, Cal Football won 5 games and lost 7 games. Go Bears! 🐻

# END SOLUTION

# BEGIN TESTS

In [17]:
0 <= cal_wins <= 10

True

In [18]:
0 <= cal_losses <= 10

True

In [19]:
# HIDDEN
cal_wins - cal_losses

-2

In [20]:
# HIDDEN
[results.item(6), results.item(1), results.item(5)] == [False, True, True]

True

# END TESTS

# END QUESTION

# BEGIN QUESTION
name: q1_5
manual: false
points:
 - 5
 - 5
 - 10

**Question 5:** Sometimes in football the two teams are equally matched and the game is quite close. Other times, it is a blowout, where the winning team wins by a large margin of victory. Let's define a **big win** to be a game in which the winning team won by more than 10 points.

Use your `final_scores` table to assign `big_wins` to an array of team names that Cal had big wins against during the 2021 football season. You may find the `is_big_win` function defined below helpful to you! **(20 Points)**

# BEGIN SOLUTION

In [21]:
def is_big_win(row):
    '''Return a boolean to describe whether or not a game (row) is a big win'''
    score_diff = row.item("Cal Score") - row.item("Opponent Score")
    
    if score_diff > 10:
        return True
    else:
        return False

big_wins = make_array()

for row in final_scores.rows: # This will help us iterate through rows of final_scores table
    opponent = row.item("Opponent") # SOLUTION
    """ # BEGIN PROMPT
    if ...: # You should use the function defined above!
    """; # END PROMPT
    # BEGIN SOLUTION NO PROMPT
    if is_big_win(row):
    # END SOLUTION
        big_wins = np.append(big_wins, opponent) # Do not change this line - Adds character to the end of some_string
big_wins

array(['Sacramento State', 'Colorado', 'Oregon State', 'Stanford'],
      dtype='<U32')

# END SOLUTION

# BEGIN TESTS

In [22]:
is_big_win(final_scores.row(2)) is True

True

In [23]:
# Make sure big_wins is an array.
import numpy as np
type(big_wins) == np.ndarray

True

In [24]:
# HIDDEN
all(big_wins == np.array(['Sacramento State', 'Colorado', 'Oregon State', 'Stanford']))

True

# END TESTS

# END QUESTION

You're done with the required section of Homework 5! Continue on to the optional section for some more practice with iterations and for loops.

Make sure to **run the submit cell located at the bottom of this notebook.**

## 2. Unrolling Loops (Optional)

**This section of HW5 is optional. Do it for your own practice, but it will not be incorporated into the final grading!**

"Unrolling" a `for` loop means to manually write out all the code that it executes.  The result is code that does the same thing as the loop, but without the structure of the loop.  For example, for the following loop:

    for num in np.arange(3):
        print("The number is", num)

The unrolled version would look like this:

    print("The number is", 0)
    print("The number is", 1)
    print("The number is", 2)


Unrolling a `for` loop is a great way to understand what the loop is doing during each step. In this exercise, you'll practice unrolling a `for` loop.


In the question below, write code that does the same thing as the given code, but with any `for` loops unrolled.  It's a good idea to run both your answer and the original code to verify that they do the same thing.  (Of course, if the code does something random, you'll get a different random outcome than the original code!)

# BEGIN QUESTION
name: q2_1
manual: false

**Optional Question 1.** Unroll the code below.

In [25]:
for joke_iteration in np.arange(3):
    print("Knock, knock.")
    print("Who's there?")
    print("Banana.")
    print("Banana who?")
print("Knock, knock.")
print("Who's there?")
print("Orange.")
print("Orange who?")
print("Orange you glad I didn't say banana?")

Knock, knock.
Who's there?
Banana.
Banana who?
Knock, knock.
Who's there?
Banana.
Banana who?
Knock, knock.
Who's there?
Banana.
Banana who?
Knock, knock.
Who's there?
Orange.
Orange who?
Orange you glad I didn't say banana?

# BEGIN SOLUTION

In [26]:
""" # BEGIN PROMPT
...
"""; # END PROMPT
# BEGIN SOLUTION NO PROMPT
print("Knock, knock.")
print("Who's there?")
print("Banana.")
print("Banana who?")
print("Knock, knock.")
print("Who's there?")
print("Banana.")
print("Banana who?")
print("Knock, knock.")
print("Who's there?")
print("Banana.")
print("Banana who?")
print("Knock, knock.")
print("Who's there?")
print("Orange.")
print("Orange who?")
print("Orange you glad I didn't say banana?")
# END SOLUTION

Knock, knock.
Who's there?
Banana.
Banana who?
Knock, knock.
Who's there?
Banana.
Banana who?
Knock, knock.
Who's there?
Banana.
Banana who?
Knock, knock.
Who's there?
Orange.
Orange who?
Orange you glad I didn't say banana?

# END SOLUTION

# END QUESTION

Congratulations, you are done with Homework 5!

**Important submission steps:** 
1. **Run** the `grader.check_all` cell below before exporting.
2. Then choose **Save Notebook** from the **File** menu, to save all the outputs.
3. Then **run the final cell**: `grader.export` 
3. Click the link to download the zip file.
4. Then submit the zip file to the corresponding assignment according to your instructor's directions. 

**It is your responsibility to make sure your work is saved before running the last cell.**